# users: [0:{name:"",country,ips[0:102.23.23]}]
users: 
#array
 - name: "camilo"
   country: "colombia"
   ips:
    - 102.123.23.24
   isActive: true
 - name: "andres"
   country: "peru"
   ips:
    - 102.123.23.40
   isActive: true
 - name: "susana"
   country: "argentina"
   ips:
    - 102.123.23.30
   isActive: true